name: demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  iconly: ^1.0.1
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5
  provider:
  flutter_iconly: ^1.0.2
  card_swiper: ^2.0.3
  fancy_shimmer_image: ^2.0.2
  flutter_staggered_grid_view: ^0.6.1
  badges: ^2.0.2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  uuid: ^3.0.6
  # Firebase
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  google_sign_in: ^5.3.0
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.14
  internet_connection_checker:
  connectivity_plus: ^2.3.5
  url_launcher: ^6.0.20

  webview_flutter: ^3.0.2



  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cat/
    - assets/images/landing/
    - assets/images/offres/
